-- Automatically generated by setup script

USE [AdventureGame]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ComponentData_RoomSlot](

    [component_data_room_slot_id] [int] IDENTITY(1,1) NOT NULL,
    [Name] [type_MediumString] not null,
    [Description] [type_LongString] not null,
    [UnidentifiedName] [type_MediumString] not null,
    [UnidentifiedDescription] [type_LongString] not null,
    [ArgumentType] [fk_component_data_argument_type_id] not null,
    [Argument] [type_ShortString] not null,

CONSTRAINT [PK_ComponentData_RoomSlot_component_data_room_slot_id] PRIMARY KEY CLUSTERED
(
    [component_data_room_slot_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[ComponentData_RoomSlot] WITH CHECK ADD CONSTRAINT [FK_Entity_ComponentData_RoomSlot_ArgumentType] FOREIGN KEY([ArgumentType])
REFERENCES [dbo].[ComponentData_ArgumentType] ([component_data_argument_type_id])
ON DELETE CASCADE
GO