-- Automatically generated by setup script

USE [AdventureGame]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ComponentData_Value](

    [component_data_value_id] [int] IDENTITY(1,1) NOT NULL,
    [GoldValue] [int] not null,
    [IsSellable] [bit] not null,

CONSTRAINT [PK_ComponentData_Value_component_data_value_id] PRIMARY KEY CLUSTERED
(
    [component_data_value_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

