-- Automatically generated by setup script

USE [AdventureGame]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ComponentData_Trigger](

    [component_data_trigger_id] [int] IDENTITY(1,1) NOT NULL,
    [Label] [type_ShortString] not null,
    [Description] [type_LongString] not null,
    [ArgumentType] [fk_component_data_argument_type_id] not null,
    [Argument] [type_ShortString] not null

CONSTRAINT [PK_ComponentData_Trigger_component_data_trigger_id] PRIMARY KEY CLUSTERED
(
    [component_data_trigger_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[ComponentData_Trigger] WITH CHECK ADD CONSTRAINT [FK_Entity_ComponentData_Trigger_ArgumentType] FOREIGN KEY([ArgumentType])
REFERENCES [dbo].[ComponentData_ArgumentType] ([component_data_argument_type_id])
ON DELETE CASCADE
GO