-- Automatically generated by setup script

USE [AdventureGame]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ComponentData_Equipped](

    [component_data_equipped_id] [int] IDENTITY(1,1) NOT NULL,
    [Arms] [fk_entity_data_container_slot_id] not null,
    [Chest] [fk_entity_data_container_slot_id] not null,
    [Hand] [fk_entity_data_container_slot_id] not null,
    [Head] [fk_entity_data_container_slot_id] not null,
    [Legs] [fk_entity_data_container_slot_id] not null,
    [MainHand] [fk_entity_data_container_slot_id] not null,
    [OffHand] [fk_entity_data_container_slot_id] not null,
    [Trinket] [fk_entity_data_container_slot_id] not null,

CONSTRAINT [PK_ComponentData_Equipped_component_data_equipped_id] PRIMARY KEY CLUSTERED
(
    [component_data_equipped_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

