-- Automatically generated by setup script

USE [AdventureGame]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ComponentData_TransitionProperties](
    [component_data_transition_properties_id] [int] IDENTITY(1,1) NOT NULL,

    [GlobalConditionId] [fk_component_data_global_condition_id] not null,
    [GoTo] [fk_component_data_go_to_id] not null,
    [ListPriority] [int] not null,
    [WhereText] [type_MediumString] not null

CONSTRAINT [PK_ComponentData_TransitionProperties_component_data_transition_properties_id] PRIMARY KEY CLUSTERED
(
    [component_data_transition_properties_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[ComponentData_TransitionProperties] WITH CHECK ADD CONSTRAINT [FK_Entity_ComponentData_TransitionProperties_GlobalConditionId] FOREIGN KEY([GlobalConditionId])
REFERENCES [dbo].[ComponentData_GlobalCondition] ([component_data_global_condition_id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ComponentData_TransitionProperties] WITH CHECK ADD CONSTRAINT [FK_Entity_ComponentData_TransitionProperties_GoTo] FOREIGN KEY([GoTo])
REFERENCES [dbo].[ComponentData_GoTo] ([component_data_go_to_id])
ON DELETE CASCADE
GO